### ISSUE TITLE
Animação da idéia de favoritos 

### ISSUE THREAD

**Issue by popcoding** [felipebweber/BTConverter#6]
@felipebweber 
Salve Felipe,
Fiz as alterações no projeto no meu local e gerei um GIF para mostrar a idéia dos favoritos (melhor que aquele desenho). Assim fica mais claro de ver. Isto é apenas uma sugestão. Como já falei na live, tem várias maneiras de se implementar a funcionalidade de favoritos. Acho que esta solução ficou bem simples.
![bit-converter-v2-pop](https://user-images.githubusercontent.com/13400453/83362950-4f34f700-a34a-11ea-9c9e-28cd2af98a65.gif)

**Comment by felipebweber** [comment]
Bom dia @popcoding, ficou mais claro que arte barroca :D. Brincadeira a parte, ficou legal e fácil.
E se tirar o picker e colocar uma table cell e fazer a seleção dos itens que se quer e adicionar. A gente já esta mudando todo a interface e acho que mudar a iteração para fica cada vez mais simples e intuitivo de usar é melhor.
Isso é uma ideia também.

![IMG_57F30F6CA5F8-1](https://user-images.githubusercontent.com/21261476/83408367-df297e00-a3e8-11ea-9bac-0039e1ded6a5.jpeg)

Esse screen shot foi de um app que baixei para ver como foi implementado a seleção das moedas.

O que achas?

**Comment by popcoding** [comment]
@felipebweber Achei a sua idéia ótima. Eu particularmente nunca implementei uma lista de seleção assim mas ela é muito comum em apps no iOS, acredito até que seja simple de se implementar, sendo muitas das funcionalidades nativas do iOS. Acho uma excelente solução, principalmente porque resolve também o problema de ordenação, dando maior flexibilidade para o usuário.

**Comment by felipebweber** [comment]
Então faremos essa implementação. Acredito que vai ficar bem legal.
